title: CamillaDSP
description: >-
  Open source audio DSP engine for real-time audio processing,
  room correction, active crossovers, and advanced filtering.
url: "https://camilladsp.com"
baseurl: ""
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
logo: "/camilladsp.svg"
masthead_title: " "

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-include-cache

paginate: 10
paginate_path: /news/page:num/

feed:
  path: feed.xml

author:
  name: "Henrik Enquist"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      share: false
      show_date: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: "2.0.x"
    values:
      layout: single
      sidebar:
        nav: "docs_v2"
  - scope:
      path: "3.0.x"
    values:
      layout: single
      sidebar:
        nav: "docs_v3"

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - vendor/
  - README.md

markdown: kramdown
kramdown:
  input: GFM

after_footer_scripts:
  - /assets/js/version-selector.js

sass:
  quiet_deps: true
  silence_deprecations:
    - import
